#+title: Drawing figures with Tikz/PGF
#+tags: LaTeX TikZ programming
#+options: toc:nil num:nil
#+LaTeX_HEADER: \usepackage{tikz,showexpl}


Figures are invaluable in capturing and communicating
information. Figures are high in information content and the skill to
draw them is essential in my trade. While there are a number of
interactive tools, it is my firm belief that a text-based description
of figures is the best approach. At least for me.

In the past, I used metafont, metapost, pstricks and asymptote. Now my
drawing tool is TikZ/PGF. It is a capable tool and sports full documentation to boot!

My TikZ figures are embedded in /.org/ files. Here is a TikZ code
snippet and the output it produces.

\begin{LTXexample}
\begin{tikzpicture}
\draw [help lines] (0,0) grid (4,2);
\draw [blue] (0,0) rectangle (1.5, 1);
\draw [red , ultra thick] (3, 0.5)
      circle [radius=0.35];
\draw [red] (3.5, 1.5) circle [radius = 0.25];
\end{tikzpicture}
\end{LTXexample}

=tikz= package must be imported with the following header.

#+BEGIN_EXAMPLE
#+LaTeX_HEADER: \usepackage{tikz}
#+END_EXAMPLE
