#+title: MonadictT
#+options: num:nil html-style:nil
* Posts
#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2018/blog-site-generator.html">
Yet Another Emacs Static Site Generator
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">
A static site generator implemented entirely in emacs.
</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2018-01-31
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/bloggen.html">
Static Blog Site Generator
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">
Descrption of elisp code which generates this blog site from a set of org-mode files,
</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2017-10-01
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2017/YetAnotherTemplatelanguageAndProcessor.html">
Yet another template language and processor
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">
A DSL for HTML documents implemented in elisp, org-mode.
</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2017-06-02
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2016/WritingAParserUsingParsec.html">
Writing a parser using Parsec
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">
My Haskell experiemnts with creating a parser for a small language.
</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2016-11-27
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2016/BloggingWithEmacsAndOrgMode.html">
Blogging with emacs and org-mode
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">
A description of emacs-based blogging workflow and unused now.
</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2016-06-19
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2015/ConfiguringXMonad.html">
Configuring XMonad
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">
A walk-through of XMonad Window Manager configuration steps
</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2015-05-20
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2014/SafeguardingSecretsWithGunPG.html">
Safeguarding Secrets with GnuPG
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">
How to store secrets on your computer and the emacs interface to access it.
</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2014-03-08
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2014/JavaForkJoinFramework.html">
Java Fork/Join Framework - an exemplar of elegant design
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">

</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2014-02-26
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2014/Ubuntu1304WifiFix.html">
Ubuntu Network Trouble
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">
Productivity tip on fixing Wi-Fi conectivity issues on Ubuntu 13.04
</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2014-02-14
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2014/JavaReferences.html">
Java References
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">

</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:  2014-01-24
</div>


#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-title">
<a href="/2018/blog-site-generator.html">
Rate-limiting Functions
</a>

</div>

#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-summary">

</div>



#+END_EXPORT

#+BEGIN_EXPORT html
<div class=" post-publish-date">
Published:
</div>


#+END_EXPORT
